import test from 'node:test';
import assert from 'node:assert/strict';
import { ROLES, roleTools, roleDenial } from '../roles.js';
const exec=(name,file)=>({name,arguments:{file_path:file},agent:{session:{header:{cwd:'C:\\work'}}}});
test('seven distinct roles and all leaves forbid dispatch',()=>{assert.equal(Object.keys(ROLES).length,7);for(const id of Object.keys(ROLES)){assert.equal(roleTools(id).has('preset_dispatch'),false);assert.match(roleDenial(id,exec('preset_dispatch')),/禁止/);assert.match(roleDenial(id,exec('plugin_manager')),/禁止/);}});
test('read-only roles deny writers and shell',()=>{for(const id of ['planner','researcher','investigator','reviewer']) {assert.equal(roleDenial(id,exec('read','src/a.js')),undefined);assert.match(roleDenial(id,exec('write','src/a.js')),/禁止/);assert.match(roleDenial(id,exec('pwsh')),/禁止/);}});
test('test author accepts tests but rejects production, config and escapes',()=>{assert.equal(roleDenial('test-author',exec('write','tests/a.test.js')),undefined);for(const file of ['src/a.js','tests/package.json','tests/vite.config.js','tests/package-lock.json','tests/.npmrc','tests/vitest.workspace.ts','..\\tests\\a.test.js']) assert.ok(roleDenial('test-author',exec('write',file)));assert.ok(roleDenial('test-author',exec('pwsh')));});
test('sensitive paths denied but example allowed',()=>{assert.ok(roleDenial('researcher',exec('read','.env')));assert.ok(roleDenial('researcher',exec('read','src/.env.local')));assert.equal(roleDenial('researcher',exec('read','.env.example')),undefined);});
test('verifier executes without direct writes; implementation can edit',()=>{assert.equal(roleDenial('verifier',exec('pwsh')),undefined);assert.ok(roleDenial('verifier',exec('edit','src/a.js')));assert.equal(roleDenial('implementer',exec('edit','src/a.js')),undefined);});
